version: 4.0.{build}
image: Visual Studio 2017
configuration: Release
build_script:
- ps: dotnet build -c Release
test_script:
- ps: pushd nClam.Net.Tests; dotnet test; popd
artifacts:
- path: nClam.Net\bin\Release\*.nupkg